### ISSUE TITLE
No collisions on some objects

### ISSUE THREAD

**Issue by AngryCarrot789** [HackerPoet/NonEuclidean#16]
The tunnel seems to be the only object with collisions, however others (like the bunny and tea pot) dont have and you can walk right through them.
![image](https://user-images.githubusercontent.com/32274404/68997117-c7e6d100-089a-11ea-9a59-49139ef6b19b.png)

**Comment by marcofs** [comment]
Objects have no collisions by default, they’re just visual models. Those tunnel collisions were hardcoded by @HackerPoet.

**Comment by AngryCarrot789** [comment]
oh right. i though it calculated the collisions using the mesh details but apparently not.

**Comment by marcofs** [comment]
> calculated the collisions using the mesh details

You can always challenge yourself and try to implement that into the engine.

**Comment by AngryCarrot789** [comment]
hmm i barely know how to draw a triangle in opengl. could give it a try tho
