### ISSUE TITLE
How do I run this?

### ISSUE THREAD

**Issue by luckyjwulf** [HackerPoet/NonEuclidean#20]
I can't find the .exe... help pls. I am kind of new to github though, so there is that.

**Comment by vbx1366** [comment]
NonEuclidian/NonEucledean.exe maybe, check it

**Comment by luckyjwulf** [comment]
Where? I can't find it.

**Comment by casualinformee** [comment]
[Download it](https://github.com/HackerPoet/NonEuclidean/archive/master.zip), unzip it (right click>Extract All>Extract), and it should be located in:
`C:\Users\[yourusername]\Downloads\NonEuclidean-master\NonEuclidean-master\NonEuclidean`
If you don't see it, Ctrl+F>Type "noneuclidean.exe".
If you still can't find it, it might have been accidentally removed by your antivirus, if you have one.

**Comment by luckyjwulf** [comment]
Yeah... I feel like an id10t...
