### ISSUE TITLE
compile with mingw32 trouble

### ISSUE THREAD

**Issue by angebrajuka** [HackerPoet/NonEuclidean#33]
Hey, any chance helping compile this with mingw32?

**Comment by angebrajuka** [comment]
never mind, if anyone needs it its
g++ *.cpp -o "output file name" -lglew32 -lopengl32 -lgdi32

**Comment by bluefield-creator** [comment]
@angelobrajuka Close this issue if it has been solved.

**Comment by KenLovesCompilingStufs** [comment]
are u using windows? bc it doesnt need any compiling stuf.
btw visit #64

**Comment by angebrajuka** [comment]
closed
