### ISSUE TITLE
Where is the executable?

### ISSUE THREAD

**Issue by LolekLiam** [HackerPoet/NonEuclidean#36]
Where is the executable? Can you provide a direct download link?

**Comment by c0zerol** [comment]
inside the folder

**Comment by pauliesnug** [comment]
I think you have to download [Visual Studio](https://visualstudio.microsoft.com) and build / run the program in there.

**Comment by Rdna123** [comment]
It is found in the executable is in NonEuclidean/NonEuclidean.exe or [https://github.com/HackerPoet/NonEuclidean/blob/master/NonEuclidean/NonEuclidean.exe](url) on GitHub

**Comment by pauliesnug** [comment]
> It is found in the executable is in NonEuclidean/NonEuclidean.exe or [https://github.com/HackerPoet/NonEuclidean/blob/master/NonEuclidean/NonEuclidean.exe](url) on GitHub

Thanks.

**Comment by bluefield-creator** [comment]
@EthanDevelops Close the issue if it has been solved.
