### ISSUE TITLE
How would you play this in VR?

### ISSUE THREAD

**Issue by OkayNamed** [HackerPoet/NonEuclidean#37]
I have an Oculus Quest 2, and I want to try to play this game in VR. Any way to do that?

**Comment by pauliesnug** [comment]
Hi! You would have to make many modifications to the original game to play it in vr.

**Comment by Axol3** [comment]
You will need to add VR support which can be pretty tricky

**Comment by ehx-v1** [comment]
While both Unity and UE4 have built-in support for VR, a lot is going on under the hood to make it work. This game uses neither, containing a custom OpenGL-based engine instead, so VR support would have to be added in from scratch. There's probably open source game engines with VR support so you could take a look at how it's done, but unfortunately I don't know any.

**Comment by bluefield-creator** [comment]
Close the issue if it was solved. And good job @ehx-v1 for explaining everything.

**Comment by pauliesnug** [comment]
@Sylack-lab I can't seem to close the issue.

**Comment by bluefield-creator** [comment]
You should see the button "comment and close" when commenting
![image](https://user-images.githubusercontent.com/48862659/103772636-1ec4e200-502a-11eb-8527-77ec7d92e4fa.png)

**Comment by pauliesnug** [comment]
I don't see that button. I think @OkayNamed has to or a contributor.

**Comment by bluefield-creator** [comment]
@EthanDevelops It is because you're not the creator of the issue 🤦‍♂️ 

Of Course OkayNamed has to close it.

**Comment by pauliesnug** [comment]
Oops 😃 . 
I'm a noob when it comes to GitHub issues and pull requests.
