### ISSUE TITLE
Textures not loading

### ISSUE THREAD

**Issue by eszn** [HackerPoet/NonEuclidean#42]
I added glew to the main directory. Textures look like this. I have opengl and everything installed on my computer.
![image](https://user-images.githubusercontent.com/30605517/120967410-a3747300-c724-11eb-9fed-60d81189716a.png)

**Comment by BigYognes** [comment]
mine just black

**Comment by the-one-with-raspberry** [comment]
> mine just black

mine too

**Comment by ehx-v1** [comment]
Possible duplicate of #35

**Comment by ToKiNoBug** [comment]
me too

**Comment by ToKiNoBug** [comment]
> > mine just black
> 
> mine too

me too

**Comment by ehx-v1** [comment]
> > > mine just black
> > 
> > 
> > mine too
> 
> me too

Possible duplicates of #13

**Comment by the-one-with-raspberry** [comment]
deep fried
