### ISSUE TITLE
Textures are messed up on my pc

### ISSUE THREAD

**Issue by todoroviclazar086** [HackerPoet/NonEuclidean#44]
You read the title, im just gonna out a picture here.
I really need help.
![image](https://user-images.githubusercontent.com/77443970/126047537-19426130-e76c-42b5-a6ef-cc22d67f5090.png)

**Comment by ehx-v1** [comment]
What was it? Another broken clone?

**Comment by todoroviclazar086** [comment]
No I downloaded it from here.
Personally I gave up cuz I found out that on amd graphics cards the textures are messed up.
I found that on an old thread
