### ISSUE TITLE
When I launch the .exe in x64 the demo is all black and my mouse cusror is stuck in place

### ISSUE THREAD

**Issue by Natvat** [HackerPoet/NonEuclidean#5]
I added glew 2.1.0 to the directory and in visual studio it is letting the project build but when starting the exe it doesnt work.

**Comment by HackerPoet** [comment]
You have to have the other folders in the same directory as the exe, otherwise it will fail to load the demo resources and everything will be black.

**Comment by Natvat** [comment]
The other folders you are talking about are the Non Euclidean resources and the glew 2.1.0 folder, or do i need to put whats inside those folders in the directory because it put those 2 folders in the same directory it was still not working  (sorry not good with this type of stuff)

**Comment by Natvat** [comment]
Ok I figured it out thanks for the help! Love the project ever since I first saw non- Euclidean use in the Stanley Parable.
