### ISSUE TITLE
program doesn't render anything

### ISSUE THREAD

**Issue by xParadoxical69** [HackerPoet/NonEuclidean#6]
When lanunched with Intel UHD Graphics 620 (integrated):
![image](https://user-images.githubusercontent.com/43796685/51096200-22b32600-17bb-11e9-9636-1f870e10f725.png)

When launched with NVIDIA GeForce 940MX:
![image](https://user-images.githubusercontent.com/43796685/51096526-5000d380-17bd-11e9-8fff-52bdddb4ab1c.png)

I have Windows 10 64bit

**Comment by babmas122** [comment]
The same thing is happening for me with Windows 10, GTX 1070, and Intel UHD Graphics

**Comment by HackerPoet** [comment]
Is this the same issue as #5 ?

**Comment by babmas122** [comment]
Yes, I wasn't able to see that issue because github defaults to showing open issues only.

**Comment by xParadoxical69** [comment]
Yes, it is same as #5.
